# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RkF6SUAFf4s4KmhX_G_xk-P1LKuCem60
"""

# 1. buat variable skalar x dan simpan
x = 15
# 2. tampilkan tipe data x
print (type(x))
# 3 buat variabel y dan simpan
y = 10
# 4 tampilkan tipe data y
print (type(y))
# 5 jumlaghkan x + y
py_sum = x + y
print (py_sum)
# 6 buat variabel x_float dan simpan suatu nia;li desimal
x_float = 3.14
# 7 jumlahkan x_floatr dengan y
float_sum = x_float + y
print (float_sum)
# 8 tampilkan tipde daata dari x_float
type(float_sum)


import torch

# 1 buat variabel skalar x dan simpan suatu nilai skalar
x_pt = torch.tensor(15)

# 2 tampilkan tipe data dari x
print(x_pt.dtype)

# 3 buat variabel skalar y dan simpan suatu nilai skalar
y_pt = torch.tensor(10)

# 4 tampilkan tipe data dari y
print(y_pt.dtype)

# 5 jumlahkan x+y
pt_sum = x_pt + y_pt
print(pt_sum)

# 6 buat variabel bernama x_float dan simpan suatu nilai desimal
x_float_pt = torch.tensor(3.14)

# 7 jumlahkan x_float dengan y
pt_float_sum = x_float_pt + y_pt
print(pt_float_sum)

# 8 tampilkan tipe data dari x_float
print(x_float_pt.dtype)

import tensorflow as tf

x_tf = tf.Variable(25)

# tampilkan tipe data dari x_tf (Tensorflow)
print(f'Type dari x_tf adalah: {type(x_tf)}')

# buat variabel skalar y_tf dan simpan suatu nilai skalar (Tensorflow)
y_tf = tf.Variable(50)

# tampilkan tipe data dari y_tf (Tensorflow)
print(f'Type dari y_tf adalah: {type(y_tf)}')

# jumlahkan x_tf + y_tf (Tensorflow)
penjumlahan3 = x_tf + y_tf
print(penjumlahan3)

# buat variabel bernama x_float_tf dan simpan suatu nilai desimal (Tensorflow)
x_float_tf = tf.Variable(3.90)

# jumlahkan x_float_tf dengan y_tf (Tensorflow)
y_float_tf = float(y_tf)
penjumlahan4 = x_float_tf + y_float_tf
print(penjumlahan4)

# tampilkan tipe data dari x_float_tf (Tensorflow)
print(f'Type dari x_float_tf adalah: {type(x_float_tf)}')