# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RkF6SUAFf4s4KmhX_G_xk-P1LKuCem60
"""

# 1. buat variable skalar x dan simpan
x = 15
# 2. tampilkan tipe data x
print (type(x))
# 3 buat variabel y dan simpan
y = 10
# 4 tampilkan tipe data y
print (type(y))
# 5 jumlaghkan x + y
py_sum = x + y
print (py_sum)
# 6 buat variabel x_float dan simpan suatu nia;li desimal
x_float = 3.14
# 7 jumlahkan x_floatr dengan y
float_sum = x_float + y
print (float_sum)
# 8 tampilkan tipde daata dari x_float
type(float_sum)

import tensorflow as tf

# 1buat
x_tf = tf.Variable(15, dtype=tf.int16)
# 2
print( x.dtype)
# 3
y_tf = tf.Variable(10, dtype=tf.int16)
# 4
print( y.dtype)
# 5
tf_sum = tf.add(x_tf, y_tf)
tf_sum